apiVersion: apps/v1
kind: Deployment
metadata:
  name: tesnginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: tesnginx
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: tesnginx
    spec:
      containers:
      - name: tesnginx-container
        image: harbor.sentuy.lan/demo/tesnginx:v2.0
        ports:
        - containerPort: 80 
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: tesnginx
  namespace: default
  labels:
    app: tesnginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
    nodePort: 31000
    protocol: TCP
  selector:
    app: tesnginx
  
